### ISSUE TITLE
error: api_authorization is not expected here

### ISSUE THREAD

**Issue by saif-ellafi** [amancevice/terraform-aws-serverless-pypi-cognito#2]
Hi around here! thanks again for this amazing implementation.

Not having luck with enabling cognito authentication:
```
│ Error: Unsupported argument
│ 
│   on poc_pypi.tf line 10, in module "serverless_pypi":
│   10:   api_authorization = "CUSTOM"
│ 
│ An argument named "api_authorization" is not expected here.
```

**Comment by saif-ellafi** [comment]
oh, I believe it is a typo in the examples, and it is expecting `api_authorization_type = "CUSTOM"` instead of `api_authorization = "CUSTOM"`

ps. same typo on both repos!

**Comment by amancevice** [comment]
You are correct — thanks for letting me know! Should be fixed in both places
